Medicine Recommendation system

In [4]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [5]:
import warnings 
warnings.filterwarnings('ignore')

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [7]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier , GradientBoostingClassifier
from sklearn.neighbors import  KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score 
from sklearn.metrics import confusion_matrix

Load Dataset

In [8]:
df = pd.read_csv('dataset/Training.csv')

In [9]:
print(df.head())
print(df.info())

   itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0
1        0          1                     1                    0          0
2        1          0                     1                    0          0
3        1          1                     0                    0          0
4        1          1                     1                    0          0

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...
1       0           0             0        0                 0  ...
2       0           0             0        0                 0  ...
3       0           0             0        0                 0  ...
4       0           0             0        0                 0  ...

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0
1           0         0             0                    0
2           0         0             0                    0
3           0         0             0                    0
4           0         0             0                    0

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0
1                     0                   0        0                     0
2                     0                   0        0                     0
3                     0                   0        0                     0
4                     0                   0        0                     0

   yellow_crust_ooze         prognosis
0                  0  Fungal infection
1                  0  Fungal infection
2                  0  Fungal infection
3                  0  Fungal infection
4                  0  Fungal infection

[5 rows x 133 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Columns: 133 entries, itching to prognosis
dtypes: int64(132), object(1)
memory usage: 5.0+ MB
None

In [10]:
df

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,(vertigo) Paroymsal Positional Vertigo
4916,0,1,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,Acne
4917,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Urinary tract infection
4918,0,1,0,0,0,0,1,0,0,0,...,0,0,1,1,1,1,0,0,0,Psoriasis
4919,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,Impetigo

In [11]:
df.size

654360

In [12]:
df.fillna("None", inplace=True)

In [13]:
df.dropna()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,(vertigo) Paroymsal Positional Vertigo
4916,0,1,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,Acne
4917,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Urinary tract infection
4918,0,1,0,0,0,0,1,0,0,0,...,0,0,1,1,1,1,0,0,0,Psoriasis
4919,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,Impetigo

In [14]:
df.drop_duplicates()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,Impetigo
403,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,Impetigo
405,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,Impetigo
406,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,Impetigo
407,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,Impetigo

In [15]:
df.shape

(4920, 133)

In [16]:
df.info

<bound method DataFrame.info of       itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0
1           0          1                     1                    0
2           1          0                     1                    0
3           1          1                     0                    0
4           1          1                     1                    0
...       ...        ...                   ...                  ...
4915        0          0                     0                    0
4916        0          1                     0                    0
4917        0          0                     0                    0
4918        0          1                     0                    0
4919        0          1                     0                    0

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0
1             0       0           0             0        0                 0
2             0       0           0             0        0                 0
3             0       0           0             0        0                 0
4             0       0           0             0        0                 0
...         ...     ...         ...           ...      ...               ...
4915          0       0           0             0        0                 0
4916          0       0           0             0        0                 0
4917          0       0           0             0        0                 0
4918          0       0           1             0        0                 0
4919          0       0           0             0        0                 0

      ...  blackheads  scurring  skin_peeling  silver_like_dusting  \
0     ...           0         0             0                    0
1     ...           0         0             0                    0
2     ...           0         0             0                    0
3     ...           0         0             0                    0
4     ...           0         0             0                    0
...   ...         ...       ...           ...                  ...
4915  ...           0         0             0                    0
4916  ...           1         1             0                    0
4917  ...           0         0             0                    0
4918  ...           0         0             1                    1
4919  ...           0         0             0                    0

      small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                        0                   0        0                     0
1                        0                   0        0                     0
2                        0                   0        0                     0
3                        0                   0        0                     0
4                        0                   0        0                     0
...                    ...                 ...      ...                   ...
4915                     0                   0        0                     0
4916                     0                   0        0                     0
4917                     0                   0        0                     0
4918                     1                   1        0                     0
4919                     0                   0        1                     1

      yellow_crust_ooze                                prognosis
0                     0                         Fungal infection
1                     0                         Fungal infection
2                     0                         Fungal infection
3                     0                         Fungal infection
4                     0                         Fungal infection
...                 ...                                      ...
4915                  0  (vertigo) Paroymsal  Positional Vertigo
4916                  0                                     Acne
4917                  0                  Urinary tract infection
4918                  0                                Psoriasis
4919                  1                                 Impetigo

[4920 rows x 133 columns]>

In [17]:
df.sample(5)

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
1845,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hepatitis B
3828,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Malaria
3704,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Jaundice
764,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Arthritis
4763,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Diabetes

In [18]:
print(df.isnull().sum())

itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
prognosis               0
Length: 133, dtype: int64

In [19]:
df.fillna(0, inplace=True)

In [20]:
df.head(2)

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection

In [21]:
df.prognosis.value_counts()

prognosis
Fungal infection                           120
Hepatitis C                                120
Hepatitis E                                120
Alcoholic hepatitis                        120
Tuberculosis                               120
Common Cold                                120
Pneumonia                                  120
Dimorphic hemmorhoids(piles)               120
Heart attack                               120
Varicose veins                             120
Hypothyroidism                             120
Hyperthyroidism                            120
Hypoglycemia                               120
Osteoarthristis                            120
Arthritis                                  120
(vertigo) Paroymsal  Positional Vertigo    120
Acne                                       120
Urinary tract infection                    120
Psoriasis                                  120
Hepatitis D                                120
Hepatitis B                                120
Allergy                                    120
hepatitis A                                120
GERD                                       120
Chronic cholestasis                        120
Drug Reaction                              120
Peptic ulcer diseae                        120
AIDS                                       120
Diabetes                                   120
Gastroenteritis                            120
Bronchial Asthma                           120
Hypertension                               120
Migraine                                   120
Cervical spondylosis                       120
Paralysis (brain hemorrhage)               120
Jaundice                                   120
Malaria                                    120
Chicken pox                                120
Dengue                                     120
Typhoid                                    120
Impetigo                                   120
Name: count, dtype: int64

In [22]:
len(df.prognosis.value_counts())

41

In [23]:
df.prognosis.unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [24]:
df.columns

Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting',
       'small_dents_in_nails', 'inflammatory_nails', 'blister',
       'red_sore_around_nose', 'yellow_crust_ooze', 'prognosis'],
      dtype='object', length=133)

In [25]:
X = df.drop('prognosis' , axis = 1)
y = df['prognosis']

In [26]:
le = LabelEncoder()
le.fit(y)
Y = le.transform(y)

In [27]:
Y

array([15, 15, 15, ..., 38, 35, 27], shape=(4920,))

In [28]:
X

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4916,0,1,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
4917,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4918,0,1,0,0,0,0,1,0,0,0,...,0,0,0,1,1,1,1,0,0,0
4919,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1

In [29]:
Y

array([15, 15, 15, ..., 38, 35, 27], shape=(4920,))

In [30]:
print(pd.Series(Y).value_counts())

15    120
20    120
22    120
3     120
36    120
10    120
34    120
13    120
18    120
39    120
26    120
24    120
25    120
31    120
5     120
0     120
2     120
38    120
35    120
21    120
19    120
4     120
40    120
16    120
9     120
14    120
33    120
1     120
12    120
17    120
6     120
23    120
30    120
7     120
32    120
28    120
29    120
8     120
11    120
37    120
27    120
Name: count, dtype: int64

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X,Y , test_size=0.2, stratify=Y, random_state=42)

In [32]:
X_train

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
3374,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1432,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3663,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3296,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3232,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2608,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2160,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1449,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3604,0,1,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0

In [33]:
X_test

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
101,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3120,1,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
694,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2374,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1163,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1982,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
832,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4325,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3973,0,1,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
3083,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [34]:
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier , GradientBoostingClassifier
from sklearn.neighbors import  KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier


models = {
   
    
    
    
    #'SVC': SVC(kernel='linear'),
    'Random_forest': RandomForestClassifier(class_weight='balanced'),
    #'Gradient_Boosting': GradientBoostingClassifier(n_estimators=100, random_state=50),
    'MultiNomialNB': MultinomialNB(),
    'KNeighbours': KNeighborsClassifier(n_neighbors=5),
    'dtc' : DecisionTreeClassifier(max_depth=14)
}

for model_name, model in models.items():
    model.fit(X_train, y_train)

   
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    train_accuracy = accuracy_score(y_train, y_train_pred)
    test_accuracy = accuracy_score(y_test, y_test_pred)

   
    cm = confusion_matrix(y_test, y_test_pred)
    acc= accuracy_score(y_test, y_test_pred)

    print("---------------")
    print(f"{model_name}")
    print(f"Train Accuracy : {train_accuracy}")
    print(f"Test Accuracy  : {test_accuracy}")
    print("Confusion Matrix:")
    print(cm)
    print("model accuracy:")
    print(acc)

---------------
Random_forest
Train Accuracy : 1.0
Test Accuracy  : 1.0
Confusion Matrix:
[[24  0  0 ...  0  0  0]
 [ 0 24  0 ...  0  0  0]
 [ 0  0 24 ...  0  0  0]
 ...
 [ 0  0  0 ... 24  0  0]
 [ 0  0  0 ...  0 24  0]
 [ 0  0  0 ...  0  0 24]]
model accuracy:
1.0
---------------
MultiNomialNB
Train Accuracy : 1.0
Test Accuracy  : 1.0
Confusion Matrix:
[[24  0  0 ...  0  0  0]
 [ 0 24  0 ...  0  0  0]
 [ 0  0 24 ...  0  0  0]
 ...
 [ 0  0  0 ... 24  0  0]
 [ 0  0  0 ...  0 24  0]
 [ 0  0  0 ...  0  0 24]]
model accuracy:
1.0
---------------
KNeighbours
Train Accuracy : 1.0
Test Accuracy  : 1.0
Confusion Matrix:
[[24  0  0 ...  0  0  0]
 [ 0 24  0 ...  0  0  0]
 [ 0  0 24 ...  0  0  0]
 ...
 [ 0  0  0 ... 24  0  0]
 [ 0  0  0 ...  0 24  0]
 [ 0  0  0 ...  0  0 24]]
model accuracy:
1.0
---------------
dtc
Train Accuracy : 0.38922764227642276
Test Accuracy  : 0.3821138211382114
Confusion Matrix:
[[24  0  0 ...  0  0  0]
 [24  0  0 ...  0  0  0]
 [24  0  0 ...  0  0  0]
 ...
 [24  0  0 ...  0  0  0]
 [24  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0 24]]
model accuracy:
0.3821138211382114

In [35]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=20,
    min_samples_split=2,
    random_state=50
)
rf.fit(X_train , y_train)
y_pred = rf.predict(X_test)
accuracy = accuracy_score(y_test , y_pred)
accuracy

1.0

In [36]:
svc = SVC(kernel = 'linear')
svc = SVC(kernel = 'linear')
svc.fit(X_train , y_train)
y_pred = svc.predict(X_test)
accuracy = accuracy_score(y_test , y_pred)
accuracy

1.0

In [37]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X, y, cv=5)
print("Accuracy:", scores.mean())

Accuracy: 0.40630081300813004

In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 20, None]
}

grid = GridSearchCV(RandomForestClassifier(), param_grid, cv=3)
grid.fit(X_train, y_train)

model = grid.best_estimator_

In [ ]:
import pickle 
pickle.dump(rf , open('model/rf.pkl','wb') )

 
pickle.dump(svc , open('model/svc.pkl','wb') )

In [ ]:
#load model 
rf = pickle.load(open("model/rf.pkl", 'rb'))
svc = pickle.load(open("model/svc.pkl", 'rb'))

In [ ]:
rf

In [ ]:
svc

In [ ]:
X_test.iloc[1].values.reshape(1,-1)

In [ ]:
rf.predict([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
svc.predict([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
X_test.iloc[7].values.reshape(1,-1)

In [ ]:
rf.predict([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
y_test

In [ ]:


precaution = pd.read_csv("dataset/precautions_df.csv")
workout = pd.read_csv("dataset/workout_df.csv")
medication = pd.read_csv('dataset/medications.csv')
diets = pd.read_csv('dataset/diets.csv')
description = pd.read_csv("dataset/description.csv")

In [ ]:
precaution.head

In [ ]:
precaution.info

In [ ]:
print(precaution.isnull().sum())
print(workout.isnull().sum())
print(medication.isnull().sum())
print(diets.isnull().sum())
print(description.isnull().sum())

In [ ]:

precaution.drop_duplicates(inplace=True)
medication.drop_duplicates(inplace=True)
workout.drop_duplicates(inplace=True)
diets.drop_duplicates(inplace=True)
description.drop_duplicates(inplace=True)

In [ ]:
precaution.fillna("No Data", inplace=True)
workout.fillna("No Data", inplace=True)
medication.fillna("No Data", inplace=True)
diets.fillna("No Data", inplace=True)
description.fillna("No Data", inplace=True)

In [ ]:
symptoms = input('Enter Your Symptoms Here..')
user_symptoms = [ s .strip().lower().replace(" ", "_") for s in symptoms.split(',')]
user_symptoms = [ sym.strip("[]'") for sym in user_symptoms]

predicted_disease = get_predicted_value(user_symptoms)
descr , pre , die , med, work = helper(predicted_disease)


print('Predicted Disease ')
print("  Prediction is:-", predicted_disease )
print('Predicted Description ')
print(descr)
print('Predicted Precaution ')
i = 1
for j in pre[0]:
    print(i , ':' , j)
    i += 1
print('Predicted Diets ')
for i in die:
    
    print(i)
    
print('Predicted Medication ')
i = 1 
for j in med:
    print(i, ":", j)
    i+= 1 
print('Predicted workout ')
i = 1 
for j in med:
    print(i, ":", j)
    i+= 1

In [ ]:
 predicted_disease

In [ ]:
%run main.py